/**
 * scripts/call_verifier.js — Deploy + call BulletproofVerifier on local Hardhat node.
 *
 * Workflow:
 *   1. Reads proof_export.json (generated by: python scripts/export_proof.py 42 8)
 *   2. Deploys BulletproofVerifier.sol
 *   3. Calls verifyView() with the proof data
 *   4. Prints the result
 *
 * Usage:
 *   npx hardhat run scripts/call_verifier.js --network hardhat
 */

const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  // ── Load proof export ───────────────────────────────────────────────────
  const exportPath = path.join(__dirname, "../proof_export.json");
  if (!fs.existsSync(exportPath)) {
    console.error("proof_export.json not found.");
    console.error("Run first:  python scripts/export_proof.py 42 8");
    process.exit(1);
  }
  const proof = JSON.parse(fs.readFileSync(exportPath, "utf8"));
  console.log(`\nLoaded proof: v in ${proof.range}, n_bits=${proof.n_bits}`);

  // ── Deploy the verifier ─────────────────────────────────────────────────
  const [deployer] = await ethers.getSigners();
  console.log(`Deploying from: ${deployer.address}`);

  const Verifier = await ethers.getContractFactory("BulletproofVerifier");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const addr = await verifier.getAddress();
  console.log(`BulletproofVerifier deployed at: ${addr}`);

  // ── Build Solidity structs from JSON ────────────────────────────────────

  function toBN(x) {
    return BigInt(x);
  }

  const points = {
    V:  proof.V.map(toBN),
    A:  proof.A.map(toBN),
    S:  proof.S.map(toBN),
    T1: proof.T1.map(toBN),
    T2: proof.T2.map(toBN),
  };

  const scalars = {
    tau_x: toBN(proof.tau_x),
    mu:    toBN(proof.mu),
    t_hat: toBN(proof.t_hat),
    ipa_a: toBN(proof.ipa_a),
    ipa_b: toBN(proof.ipa_b),
  };

  const challenges = {
    y:     toBN(proof.challenge_y),
    z:     toBN(proof.challenge_z),
    x:     toBN(proof.challenge_x),
    delta: toBN(proof.delta),
    z2:    toBN(proof.z2),
    x2:    toBN(proof.x2),
  };

  const ipaFinal = {
    P_final: proof.P_final.map(toBN),
    G_final: proof.G_final.map(toBN),
    H_final: proof.H_final.map(toBN),
  };

  // ── Call verifyView ─────────────────────────────────────────────────────
  console.log("\nCalling verifyView()...");
  const result = await verifier.verifyView(
    points,
    scalars,
    challenges,
    ipaFinal,
    proof.n_bits
  );

  console.log(`\n${"=".repeat(50)}`);
  console.log(`  On-chain verification result: ${result ? "✓ VALID" : "✗ INVALID"}`);
  console.log(`  Proof range: ${proof.range}`);
  console.log(`  n_bits: ${proof.n_bits}`);
  console.log(`${"=".repeat(50)}\n`);

  if (!result) {
    process.exitCode = 1;
  }

  // ── Also call verify() (with event) ─────────────────────────────────────
  console.log("Calling verify() (emits event)...");
  const tx = await verifier.verify(
    points, scalars, challenges, ipaFinal, proof.n_bits
  );
  const receipt = await tx.wait();

  // Decode ProofVerified event
  const iface = verifier.interface;
  for (const log of receipt.logs) {
    try {
      const decoded = iface.parseLog(log);
      if (decoded && decoded.name === "ProofVerified") {
        console.log(`Event ProofVerified:`);
        console.log(`  prover: ${decoded.args.prover}`);
        console.log(`  valid:  ${decoded.args.valid}`);
        console.log(`  n_bits: ${decoded.args.n_bits}`);
      }
    } catch (_) {}
  }

  console.log(`\nGas used for verify(): ${receipt.gasUsed.toString()}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
