"""
scripts/export_proof.py — Export a Python range proof for Solidity verification.

The Solidity contract uses BN128 precompiles (ecAdd=0x06, ecMul=0x07) to
verify the same math. This script computes the intermediate folded values
that the Solidity verifier needs, so the contract can verify with minimal gas.

Exported JSON format:
  - All curve points as [x, y] pairs (uint256)
  - All scalars as uint256 hex strings
  - Pre-computed Fiat-Shamir challenges (y, z, x)
  - Pre-computed folded IPA generators and commitment
"""

import sys, json
sys.path.insert(0, "src")

from ec_math import (
    G, H, ec_add, ec_mul, ORDER, get_generator_vector, point_to_bytes
)
from range_proof import prove, verify, power_vector, mod_inv
from transcript import Transcript


def point_to_pair(P):
    """Convert py_ecc point to [x, y] list of ints (for JSON / Solidity)."""
    if P is None:
        return [0, 0]
    return [int(P[0]), int(P[1])]


def export_for_solidity(proof) -> dict:
    """
    Given a RangeProof, compute all intermediate values the Solidity
    BulletproofVerifier.sol needs and return them as a JSON-serialisable dict.

    The Solidity contract will:
      1. Re-derive challenges from proof components (or accept them trusted)
      2. Check the polynomial identity using ecMul + ecAdd
      3. Check the folded IPA condition: a*G_final + b*H_final == P_final
    """
    n = proof.n_bits
    G_vec = get_generator_vector(n, b"bulletproof_G_vec_v1")
    H_vec = get_generator_vector(n, b"bulletproof_H_vec_v1")

    # ── Recompute Fiat-Shamir challenges (same as verifier) ──────────────
    t = Transcript()
    t.append_point(b"V",   proof.V)
    t.append_point(b"A",   proof.A)
    t.append_point(b"S",   proof.S)
    y = t.get_challenge(b"y")
    z = t.get_challenge(b"z")
    t.append_point(b"T_1", proof.T_1)
    t.append_point(b"T_2", proof.T_2)
    x = t.get_challenge(b"x")

    # ── Compute delta(y,z) for polynomial identity check ─────────────────
    z2 = (z * z) % ORDER
    x2 = (x * x) % ORDER
    y_n    = power_vector(y, n)
    two_n  = power_vector(2, n)
    sum_y  = sum(y_n) % ORDER
    sum_2  = sum(two_n) % ORDER
    delta  = ((z - z2) % ORDER * sum_y - z2 * z % ORDER * sum_2) % ORDER

    # ── Compute P commitment for IPA verifier ────────────────────────────
    y_inv   = mod_inv(y)
    y_inv_n = power_vector(y_inv, n)
    H_prime = [ec_mul(y_inv_n[i], H_vec[i]) for i in range(n)]

    P = ec_add(proof.A, ec_mul(x, proof.S))
    for i in range(n):
        P = ec_add(P, ec_mul((-z) % ORDER, G_vec[i]))
        coeff = (z * y_n[i] + z2 * two_n[i]) % ORDER
        P = ec_add(P, ec_mul(coeff, H_prime[i]))
    P = ec_add(P, ec_mul((-proof.mu) % ORDER, H))

    # ── Fold IPA: iterate the same reduction as ipa_verify ───────────────
    G_fold = list(G_vec)
    H_fold = list(H_prime)
    P_fold = P

    t.append_scalar(b"tau_x", proof.tau_x)
    t.append_scalar(b"mu",    proof.mu)
    t.append_scalar(b"t_hat", proof.t_hat)

    ipa_challenges = []
    for L, R in zip(proof.ipa.L_vec, proof.ipa.R_vec):
        t.append_point(b"L", L)
        t.append_point(b"R", R)
        xi     = t.get_challenge(b"x_ipa")
        xi_inv = pow(xi, ORDER - 2, ORDER)
        xi2    = (xi * xi)     % ORDER
        xi2inv = (xi_inv * xi_inv) % ORDER
        ipa_challenges.append((xi, xi_inv))

        # Fold P
        P_fold = ec_add(ec_add(ec_mul(xi2, L), P_fold), ec_mul(xi2inv, R))

        # Fold generators
        half   = len(G_fold) // 2
        G_fold = [ec_add(ec_mul(xi_inv, G_fold[i]), ec_mul(xi, G_fold[i + half]))
                  for i in range(half)]
        H_fold = [ec_add(ec_mul(xi,     H_fold[i]), ec_mul(xi_inv, H_fold[i + half]))
                  for i in range(half)]

    G_final = G_fold[0]
    H_final = H_fold[0]

    # ── Sanity check: a*G_final + b*H_final should equal P_final ─────────
    expected = ec_add(ec_mul(proof.ipa.a, G_final), ec_mul(proof.ipa.b, H_final))
    assert (int(expected[0]) == int(P_fold[0]) and
            int(expected[1]) == int(P_fold[1])), "IPA final check failed in export!"

    # ── Build export dict ─────────────────────────────────────────────────
    return {
        "_comment": "Generated by export_proof.py for BulletproofVerifier.sol",
        "n_bits":  n,
        "range":   f"[0, {2**n})",

        # Proof points (5 curve points)
        "V":   point_to_pair(proof.V),
        "A":   point_to_pair(proof.A),
        "S":   point_to_pair(proof.S),
        "T1":  point_to_pair(proof.T_1),
        "T2":  point_to_pair(proof.T_2),

        # Proof scalars
        "tau_x": proof.tau_x,
        "mu":    proof.mu,
        "t_hat": proof.t_hat,

        # IPA points and final scalars
        "L_vec": [point_to_pair(L) for L in proof.ipa.L_vec],
        "R_vec": [point_to_pair(R) for R in proof.ipa.R_vec],
        "ipa_a": proof.ipa.a,
        "ipa_b": proof.ipa.b,

        # Fiat-Shamir challenges (pre-computed off-chain)
        "challenge_y": y,
        "challenge_z": z,
        "challenge_x": x,

        # Pre-computed constants for Solidity polynomial identity check
        "delta": delta,
        "z2":    z2,
        "x2":    x2,

        # Pre-folded IPA inputs for efficient Solidity verification
        "P_final": point_to_pair(P_fold),
        "G_final": point_to_pair(G_final),
        "H_final": point_to_pair(H_final),

        # Generator points (for full on-chain re-derivation if needed)
        "G_vec":   [point_to_pair(p) for p in G_vec],
        "H_prime": [point_to_pair(p) for p in H_prime],

        # BN128 fixed generators (for Solidity reference)
        "G_point": [1, 2],
        "H_point": point_to_pair(H),
    }


if __name__ == "__main__":
    """
    CLI: python scripts/export_proof.py <value> <n_bits>
    Example: python scripts/export_proof.py 42 8
    """
    import argparse
    parser = argparse.ArgumentParser(description="Export a range proof for Solidity")
    parser.add_argument("value",  type=int, default=42,  nargs="?", help="Secret value to prove")
    parser.add_argument("n_bits", type=int, default=8,   nargs="?", help="Bit range (power of 2)")
    parser.add_argument("-o", "--output", default="proof_export.json", help="Output JSON file")
    args = parser.parse_args()

    print(f"[export_proof] Proving v={args.value} in [0, {2**args.n_bits}), n={args.n_bits} bits...")
    proof = prove(args.value, n_bits=args.n_bits)

    valid = verify(proof)
    print(f"[export_proof] Python verify: {valid}")
    assert valid, "Proof failed Python verification — aborting export"

    data = export_for_solidity(proof)
    with open(args.output, "w") as f:
        json.dump(data, f, indent=2)
    print(f"[export_proof] Written to: {args.output}")
    print(f"[export_proof] Ready for: npx hardhat run scripts/call_verifier.js")
